services:
  admin:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.admin
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '4003:5432'
    environment:
      - POSTGRES_USER=yvon
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=yvonne
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
