FROM oven/bun:latest AS build

WORKDIR /app

COPY . .

RUN bun install --ci --ignore-scripts

WORKDIR /app/apps/admin

RUN bun run build

FROM nginx:alpine

COPY --from=build /app/apps/admin/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
